### ISSUE TITLE
Current GFS Vtable does not work with pre-20150114 data

### ISSUE THREAD

**Issue by mgduda** [wrf-model/WPS#137]
Apparently, older GFS datasets do not contain an MSLET field, only a smoothed PRMSL field. The current `Vtable.GFS` will therefore fail to identify the PRMSL field as the source of the PMSL field in these datasets. This issue was identified in this forum post: https://forum.mmm.ucar.edu/phpBB3/viewtopic.php?p=15793&sid=b53c4e3ea0dbcd94b51056de32f3d2d6#p15793 .

**Comment by jimbresch** [comment]
This issue was addressed when WPS4.1 was released in 2019 with comments added to the revised Vtable. Users need to edit the Vtable when using older GFS/GDAS files. Other solutions were considered, but with the way ungrib is constructed none of the changes make sense. For example, the Vtable contains no model identification. The date string is not passed down to the variable decoding logic. The GFS fields can be in random order within the file so one can't count on a certain PMSL field appearing first. Finally, any if-testing for date or field would have to be done for every field and every input model which would be a waste of CPU time. So, users will have to edit the Vtable themselves when using old GFS files.
