### ISSUE TITLE
Intermediate format : Possible inconsistency between code and user guide

### ISSUE THREAD

**Issue by Enzoupi** [wrf-model/WPS#143]
Hi everybody !

I would like to report a possible inconsistency between the User manual and the code:

As a reference for the latest user guide, I am using [https://www2.mmm.ucar.edu/wrf/users/docs/user_guide_V4/WRFUsersGuide.pdf](https://www2.mmm.ucar.edu/wrf/users/docs/user_guide_V4/WRFUsersGuide.pdf). It might not be the latest but it is at least the latest I have found.

On section 3-34 one can read :

```
integer :: iproj
! Code for projection of data in array:
! 0 = cylindrical equidistant
! 1 = Mercator
! 3 = Lambert conformal conic
! 4 = Gaussian (global only!)
! 5 = Polar stereographic

```
Whereas in a Fortran routine designed to write intermediate file it is written : 

```

   ! Projection codes for proj_info structure:
   integer, public, parameter  :: PROJ_LATLON = 0
   integer, public, parameter  :: PROJ_LC = 1
   integer, public, parameter  :: PROJ_PS = 2
   integer, public, parameter  :: PROJ_PS_WGS84 = 102
   integer, public, parameter  :: PROJ_MERC = 3
   integer, public, parameter  :: PROJ_GAUSS = 4
   integer, public, parameter  :: PROJ_CYL = 5
   integer, public, parameter  :: PROJ_CASSINI = 6
   integer, public, parameter  :: PROJ_ALBERS_NAD83 = 105 
   integer, public, parameter  :: PROJ_ROTLL = 203

```

Regarding option number 1, rd_intermediate give reason to the second listing. Moreover, using the second list of option, no offset was found between the field and the topography !

Wishing you all the best,

Enzo

**Comment by mgduda** [comment]
For a bit of background, the second set of projection numbers you've show is used internally when tracking map projections that are supported by the `map_utils` module ([geogrid/src/module_map_utils.F](https://github.com/wrf-model/WPS/blob/v4.1/geogrid/src/module_map_utils.F)), while the first set is used in the intermediate format ([metgrid/src/read_met_module.F](https://github.com/wrf-model/WPS/blob/v4.1/metgrid/src/read_met_module.F)).

Both the intermediate file format (at least, format versions 3 and 4) as well as the `map_utils` module predate the the WPS, and we preserved the differences in projection numbers when developing the WPS. This means that when reading intermediate files, we need to translate from one set of projection numbers to another: see, e.g., the Lambert conformal reading code, where we [translate from projection number 3 to PROJ_LC](https://github.com/wrf-model/WPS/blob/v4.1/metgrid/src/read_met_module.F#L295-L297).

Because we perform the reverse translation, e.g., when [writing an intermediate record](https://github.com/wrf-model/WPS/blob/v4.1/metgrid/src/write_met_module.F#L312-L322) on an Lambert conformal projection, it's necessary to use the projection numbers from [geogrid/src/misc_definitions_module.F](https://github.com/wrf-model/WPS/blob/v4.1/geogrid/src/misc_definitions_module.F) if the [write_met_module](https://github.com/wrf-model/WPS/blob/v4.1/metgrid/src/write_met_module.F) code is used. However, if some other code is used (perhaps a Python script, etc.), it's probably easiest to ignore the projection numbers in [misc_definitions_module](https://github.com/wrf-model/WPS/blob/v4.1/geogrid/src/misc_definitions_module.F) and to simply use the projection numbers from section 3-34 of the Users's Guide.

I will certainly agree, though, that this switching between projection codes is unnecessarily confusing!

**Comment by Enzoupi** [comment]
Hi @mgduda !


First of all, thank you very much for your complete reply and sorry for not answering earlier. I also want to thank you for the historical perspective which often brings a lot of sense to how a code is actually coded :)

I took time in answering because I had some trouble understanding what was going on (which of course was stupid and basic ) !

In short, I switched from writing intermediate files by myself in python to write them through a Fortran routine -- from which you might be the author btw -- pythonified with `f2py`. And, within this routine the mapping from map_utils code to the other one is done internally. And of course, I continued to use the first set of codes without noticing...

Thanks a lot for your help and sorry for the fake bug report !

All the best,

Enzo
