### ISSUE TITLE
Issue with iconeu data

### ISSUE THREAD

**Issue by claort** [wrf-model/WPS#225]
Hi 
One question. I downloaded the last versione of WPS. Is It ready to run wrf with iconEU data or Need some other step? 
For example i saw some reference to HSURF variabile to be added for each time step but i didn t find this variabile in the Vtable.Icon.
Can you explain the step to be followed ?

I already run wrf with iconEU but i found some strange data in the Rain so i would check again the configuration (i use in the namelist.input nummetgrid 61 and soil level 6)
Tks

**Comment by weiwangncar** [comment]
@claort Please see discussions in PR#[221](https://github.com/wrf-model/WPS/pull/221) and PR#[154](https://github.com/wrf-model/WPS/pull/154). In addition, you can post the question in the [Forum](https://forum.mmm.ucar.edu/).

**Comment by weiwangncar** [comment]
@claort As long as you download the right data (as the example download script shows in PR#154, and it is not the native mesh data), and use the Vtables newly added, the WPS/ungrib program is able to process the data, as a few of us have demonstrated.

**Comment by claort** [comment]
Ok i downloaded the data using the same script .sh and i run with success WPS with ICONEU.
My doubt was because i found some Rain without any Sense respect to the same simulation made with GFS.

But if additional steps are not Need once i download the right grib file from opendata /dwd icon EU/ It doesn t make Sense ti keep in the vtable text bottom part the remarks: some field time invariant Need to ingest for each time step.

**Comment by WQadam** [comment]
Hi Claort, 

The time invariant remark on the vtable is because of HSURF. The opendata server only as 1 file for the whole run for this variable but metgrid and wrf requires it to be in every timestep. I havent double checked with the download script on PR#154 but i would image this downloads this variable for every time step and then changes the time to the model forecast time rather than the initialization time that is within the only HSURF file on the open data server.

If you look at the example model level download script for ICON-global in PR#221 on my comment that i have tried to split up the steps within the download script. Note for icon eu you dont need to do the regrid step within that download script. You will see in that script i set the time within the last step using cdo so all the forecast data has the same time. Hope that makes sense.

In terms of the rain comments then yes the icon will have rain in different places compared to the GFS due to different resolutions and data assimilation between the 2 models.

**Comment by claort** [comment]
@WQadam many thanks for the clarification. 
I have done different runs with iconEU all Ok.  About HSURF i tried to adjust the data using grib_set and It works.
About Rain i believe It depends in the configuration (mp and radiation mainly) changing these and making some test i found different result between gfs and iconEU.
Tks again
